name: mobile_app_labamu
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  http: ^0.13.1
  bloc: ^7.1.0
  intl: ^0.17.0
  meta: ^1.3.0
  rxdart: ^0.27.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.2.8
  grouped_list: ^6.0.0
  date_picker_plus: ^4.1.0
  centrifuge: ^0.8.0
  package_info_plus: ^3.1.2
  device_info_plus: ^10.0.1
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  encrypt_shared_preferences: ^0.5.0
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/